### ISSUE TITLE
Memleax detect overwhelming memory leak while running curl program

### ISSUE THREAD

**Issue by Taymindis** [WuBingzheng/memleax#11]
I have using memleax to attach my C application. My application has CURL with SSL for push notification. if i use valgrind for one time program, It did not detect any memory leak. 

but if I attached program to memleax, It detect overwhelming memory leak and kill my program as well. 

Scenario to trigger:
1. Create a curl with SSL program with scanf hooking from start and end, attached pid to memleax. 

[memleax_issue.txt](https://github.com/WuBingzheng/memleax/files/653728/memleax_issue.txt)

**Comment by WuBingzheng** [comment]
Thanks for your feedback.

memleax works differently with valgrind, so they may give different results.

Did you set '-e' option? What value to you set?
It seems that memleax run only for 7 seconds, and killed your program then?

I will write a program using libcurl later and try it. However it's very nice if you give me an example code.

**Comment by Taymindis** [comment]
HI WuBingzheng, 

Sorry For the late response.

`
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <curl/curl.h>
#include <cjson/cJSON.h>

int main(void)
{
  char str1[5], str2[5];
  printf("type any character press enter proceed....");
  scanf("%s", str1);
  CURL *curl;
  CURLcode res;
  long http_code;

  curl = curl_easy_init();
  if(curl) {
    curl_easy_setopt(curl, CURLOPT_URL, "http://www.google.com.sg");
    /* example.com is redirected, so we tell libcurl to follow redirection */
    curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);

    /* Perform the request, res will get the return code */
    res = curl_easy_perform(curl);

    curl_easy_getinfo (curl, CURLINFO_RESPONSE_CODE, &http_code);

    printf("http code = %ld\n", http_code);
    /* Check for errors */
    if(res != CURLE_OK)
      fprintf(stderr, "curl_easy_perform() failed: %s\n",
              curl_easy_strerror(res));

    /* always cleanup */
    curl_easy_cleanup(curl);
    curl_global_cleanup();
  }

  printf("check memleax.. \ntype any character press enter to finish");
  scanf("%s", str2);
  return 0;
}
`

And i find the pid then `sudo memleax -e 7  <pid>`

You are right, I run for 7sec expired, and memleax show me all the memory expired but never free.

**Comment by WuBingzheng** [comment]
Thanks for your code. Now I think that the problem may be at the NSS of glibc.

I wrote a smaller program, which only calls `getaddrinfo()` and `freeaddrinfo()`. Then I use memleax to attach it. memleax detects the memory allocation at `getaddrinfo()`, but dose not detect the memory free at `freeaddrinfo()`.

Then I wrote another program, which calls `getaddrinfo()` and `freeaddrinfo()` many times. memleax detects the memory allocation only at the first `getaddrinfo()`.

From the output of memleax, it's `nss_parse_service_list()` who allocates memory.
Then I use GDB to debug the program and make breakpoint at it. The program stops here only at the first time of `getaddrinfo()`.

    0x00007f2e526db220  libc-2.17.so  malloc()+0
    0x00007f2e527630a3  libc-2.17.so  nss_parse_service_list()+147
    0x00007f2e5276371d  libc-2.17.so  __nss_database_lookup()+797
    0x00007f2e52765077  libc-2.17.so  __GI___nss_services_lookup2()+87
    0x00007f2e5276cc18  libc-2.17.so  getservbyname_r()+520
    0x00007f2e52736ee4  libc-2.17.so  gaih_inet_serv.isra.3()+116
    0x00007f2e5273788e  libc-2.17.so  gaih_inet()+2350
    0x00007f2e5273b2cd  libc-2.17.so  getaddrinfo()+253
    0x0000000000400788  a.out  main()+136

In your memleax_issue.txt, there are also many memory-leaks at `getaddrinfo()`. While there is no backtrace as complete as this.

So I think there maybe a memory-pool or some-cache in glibc, which allocates memory at first time, and reuse the memory later, so it will never free the memory.

So, there is not-freed memory indeed! However this is ok.

You can run your program, and wait for it to do the host-resolve work. And then run memleax to attach it, to skip the not-freed memory.

I will test valgrind tomorrow.

And I did not re-produce the "memleax kills the target process" case.

**Comment by WuBingzheng** [comment]
I try valgrind to monitor `getaddrinfo()` and `freeaddrinfo()` today, and get this:

    --13197-- Discarding syms at 0x55f9240-0x5600454 in /usr/lib64/libnss_files-2.17.so due to mu
    --13197-- Discarding syms at 0x580b100-0x580e590 in /usr/lib64/libnss_dns-2.17.so due to munm
    --13197-- Discarding syms at 0x5a13a40-0x5a22854 in /usr/lib64/libresolv-2.17.so due to munma
    ==13197== Invalid free() / delete / delete[] / realloc()
    ==13197==    at 0x4C2AD17: free (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
    ==13197==    by 0x4F9963B: __libc_freeres (in /usr/lib64/libc-2.17.so)
    ==13197==    by 0x4A246B4: _vgnU_freeres (in /usr/lib64/valgrind/vgpreload_core-amd64-linux.s
    ==13197==    by 0x4E6DE2A: __run_exit_handlers (in /usr/lib64/libc-2.17.so)
    ==13197==    by 0x4E6DEB4: exit (in /usr/lib64/libc-2.17.so)
    ==13197==    by 0x4E56B1B: (below main) (in /usr/lib64/libc-2.17.so)
    ==13197==  Address 0x51f03d0 is 0 bytes inside data symbol "noai6ai_cached"

It seems that libc-nss frees some memory at `__run_exit_handlers()` after `exit()`.
`memleax` stops monitoring the target process at its `exit()`, so it misses these `free()`, so it thinks this memory is leaked.

There is a way to avoid `memleax` reporting this kind leak.
You run `memleax` to attaching the target progress after it call `getaddrinfo()` first time. This skips the initial-memory allocation. Hope this helps you.

Still, I have not re-produced the "memleax kills the target process" case.

**Comment by Taymindis** [comment]
Hi Wu Bing Zheng, 

Thanks for your advise, i will take note and discuss with my team member.
