### ISSUE TITLE
Error: open map of /drm: No such file or directory

### ISSUE THREAD

**Issue by tibor95** [WuBingzheng/memleax#12]
Hi,
I tried to use your tool, but got:

$memleax 26096
Error: open map of /drm: No such file or directory

It is 64bit Arch Linux.

Please advice

**Comment by WuBingzheng** [comment]
It seems that you used a stale version.
Please try the latest version : https://github.com/WuBingzheng/memleax/releases/tag/v1.0.1 .

**Comment by tibor95** [comment]
Yes, you are right, with new version it works fine.
If was PKGBUILD from Arch Linux, and I had not noticed it is outdated, sorry :)
