### ISSUE TITLE
Memleax now available in FreeBSD ports collection

### ISSUE THREAD

**Issue by tabrarg** [WuBingzheng/memleax#14]
Hi,

I have added memleax to the FreeBSD ports collection, meaning it can now be installed on FreeBSD using:

`pkg install memleax` to install the package or `cd /usr/ports/devel/memleax && make install clean` to make and install from source.

Thanks for building a great tool!

Guy

**Comment by WuBingzheng** [comment]
Thanks for doing this!

But I find that `--disable-debug_line` is used, so filename and line number can not be showed in output of memleax. Why do you disable this?

**Comment by tabrarg** [comment]
Hi, np!

I had to add that option as I couldn't get it to build on FreeBSD 10.3 (11.0 is fine). I get this error:
`libdwarf is missing.
Error: libdw or libdwarf is required.
Try '--disable-debug_line' to disable it.`

I added a dependency to libdwarf.a from the devel/libdwarf port, but it still fails with this error.

**Comment by WuBingzheng** [comment]
I know this issue and write it in README: https://github.com/WuBingzheng/memleax#build-from-source :

NOTE: On FreeBSD 10.3, there are built-in libelf and libdwarf already. However another libelf and libdwarf still can be installed by pkg. memleax works with `built-in libelf` and `pkg libdwarf`. So you should install libdwarf by pkg, and must not install libelf by pkg.

I am not familiar with FreeBSD and do not know the reason.
But I think debug-line is important for debugging and it's better not to be disabled.
The option `--disable-debug_line` is used only when libdwarf is not available for your distribution in case.

Would you like to fix this and update it to FreeBSD ports collection?

Thanks

**Comment by tabrarg** [comment]
Yeah, I read the README, what I'm saying is that on FreeBSD 10.3 it doesn't work even after pkg libdwarf has been installed. Are there sure there are no other steps when you tried 10.3?

What I can do for now is set it to built with --disable-debug-line removed on FreeBSD 11.0 because it does work fine there, it would be good to find a solution for 10.3 also.

Cheers!

**Comment by WuBingzheng** [comment]
I will build a new FreeBSD 10.3 VM to try this after work.

**Comment by WuBingzheng** [comment]
I find the problem. libz is need by libdwarf in FreeBSD.
It's strange that I did not set libz before and it worked.

I have fix this and release a new version v1.0.3.
Please try this and update at FreeBSD port collection.

I have another question because I am not familiar with FreeBSD.
Since you put memleax to FreeBSD port collection, I try it by `cd /usr/ports/devel/memleax && make install clean`, and it works!!!
But how should I use `pkg install memleax` ? Should I do something to update package repo? I run `pkg update` but nothing happens.

**Comment by tabrarg** [comment]
Great news :)

I have updated the port locally to 1.0.3 and it seems OK, I will submit the changes for review. If you like you can test it by downloading the shar file [here](https://expirebox.com/download/ed000101bd7c430356e49eb3c15fc011.html). 

You need to copy the shar file into /usr/ports/devel/ then backup the old memleax with `mv /usr/ports/devel/memleax /usr/ports/devel/memleax_v1.0.2`, extract the shar with `cd /usr/ports/devel/ && sh memleax.shar` and finally install with `cd /usr/ports/devel/memleax && make install clean`

Regarding pkg, it will update the repo automatically whenever you try and install something:
```
#>pkg install memleax
Updating FreeBSD repository catalogue...
Fetching meta.txz: 100%    944 B   0.9kB/s    00:01
Fetching packagesite.txz: 100%    6 MiB   5.9MB/s    00:01
Processing entries: 100%
FreeBSD repository update completed. 25860 packages processed.
......
The most recent version of packages are already installed
```

**Comment by WuBingzheng** [comment]
I got this:

    # pkg install memleax
    Updating FreeBSD repository catalogue...
    FreeBSD repository is up-to-date.
    All repositories are up-to-date.
    pkg: No packages available to install matching 'memleax' have been found in the repositories

Should I have install another repo?

**Comment by tabrarg** [comment]
Hey,

The new version is available in the ports tree now, you can get it with:
`portsnap fetch update && cd /usr/ports/devel/memleax && make install clean`. You will need to `make deinstall` the old version first if you've got it installed.

I'm looking into why the binary package hasn't appear yet.

Cheers

**Comment by tabrarg** [comment]
It seems that the way FreeBSD packages are built has changed - it should go in shortly, and will be updated [here](http://portsmon.freebsd.org/portoverview.py?category=devel&portname=memleax&wildcard=).

**Comment by WuBingzheng** [comment]
Thanks for your work. I will add this to README later.
