### ISSUE TITLE
Can't get this to detect any leaks.

### ISSUE THREAD

**Issue by darrylo** [WuBingzheng/memleax#15]
This is under 64-bit RedHat 6 (yes, I know it's old, but it's what I have).   memleax sources were obtained from the downloadable .tar.gz.

Perhaps I'm misunderstanding how this is supposed to work, but memleax does not detect any leaks on a program that (1) waits for the user to attach memleax, (2) after memleax is attached, allocates memory that is never freed, (2) and sleeps 30 seconds.  Even though the unfreed memory blocks are allocated after memleax is attached, nothing is ever reported:

    $ memleax -e 2 24838
    == Begin monitoring process 24838...

    == Target process exit.
    == No expired memory blocks.

Test code below.  Use by:

* Compile with `g++ -g test.cc`

* Run `./a.out`

* In another window, attach memleakx to a.out.

* Go back to the window where `a.out` is running, and press [Enter].  Once you do that, test memory blocks are allocated, and the program sleeps for 30 seconds.

* memleax never reports any leaks, even though the blocks were allocated after memleax was attached, and live for more than the default 10 seconds.

Test code:

    #include <cstdio>
    #include <cstdlib>
    #include <unistd.h>

    class testclass {
    public:
        int             a;
        int             b;

        testclass(void)
        {
            a = 0;
            b = 0;
        }
    };

    int main()
    {
        testclass  *t;
        char       buf[1000];
        void       *m;

        // Wait for [Enter] to be pressed
        printf("Start? ");
        fflush(stdout);
        fgets(buf, sizeof(buf) - 1, stdin);

        printf("starting\n");
        t = new testclass();
        m = malloc(200);
        sleep(30);
        printf("done\n");
        return 0;
    }

**Comment by WuBingzheng** [comment]
I follows your steps exactly at CentOS6 and catch the memory leak:

    [root@centos6 memleax]# ./memleax -e 2 `pgrep a.out`
    == Begin monitoring process 1546...
    CallStack[1]: memory expires with 8 bytes, backtrace:
        0x00007fb2bde88ac0  libc-2.12.so  malloc()+0
        0x00007fb2be6f90cd  libstdc++.so  _Znwm()+29
        0x000000000040083d  a.out  main()+89  /root/test.c:30
    CallStack[2]: memory expires with 200 bytes, backtrace:
        0x00007fb2bde88ac0  libc-2.12.so  malloc()+0
        0x0000000000400859  a.out  main()+117  /root/test.c:31

    == Target process exit.
    == Callstack statistics: (in ascending order)

    CallStack[2]: may-leak=1 (200 bytes)
        expired=1 (200 bytes), free_expired=0 (0 bytes)
        alloc=1 (200 bytes), free=0 (0 bytes)
        freed memory live time: min=0 max=0 average=0
        un-freed memory live time: max=30
        0x00007fb2bde88ac0  libc-2.12.so  malloc()+0
        0x0000000000400859  a.out  main()+117  /root/test.c:31

    CallStack[1]: may-leak=1 (8 bytes)
        expired=1 (8 bytes), free_expired=0 (0 bytes)
        alloc=1 (8 bytes), free=0 (0 bytes)
        freed memory live time: min=0 max=0 average=0
        un-freed memory live time: max=30
        0x00007fb2bde88ac0  libc-2.12.so  malloc()+0
        0x00007fb2be6f90cd  libstdc++.so  _Znwm()+29
        0x000000000040083d  a.out  main()+89  /root/test.c:30

I can not think out any possible reasons now...

**Comment by darrylo** [comment]
Well, that's weird.

I just did a quick strace, and memleax does have issues:

    18:38:29.471837 ptrace(PTRACE_SETOPTIONS, 25015, 0, PTRACE_O_TRACEFORK|PTRACE_O_TRACEVFORK|PTRACE_O_TRACECLONE) = 0
    18:38:29.471875 ptrace(PTRACE_PEEKTEXT, 25015, 0x61fb07aa50, [0x2]) = -1 EIO (Input/output error)
    18:38:29.471901 ptrace(PTRACE_POKETEXT, 25015, 0x61fb07aa50, 0xffffffffffffffcc) = -1 EIO (Input/output error)
    18:38:29.471935 ptrace(PTRACE_PEEKTEXT, 25015, 0x61fb07b8b0, [0x2]) = -1 EIO (Input/output error)
    18:38:29.471959 ptrace(PTRACE_POKETEXT, 25015, 0x61fb07b8b0, 0xffffffffffffffcc) = -1 EIO (Input/output error)
    18:38:29.471991 ptrace(PTRACE_PEEKTEXT, 25015, 0x61fb07bdb0, [0x2]) = -1 EIO (Input/output error)
    18:38:29.472016 ptrace(PTRACE_POKETEXT, 25015, 0x61fb07bdb0, 0xffffffffffffffcc) = -1 EIO (Input/output error)
    18:38:29.472115 ptrace(PTRACE_PEEKTEXT, 25015, 0x61fa8168c0, [0x7ffcb906aec0]) = -1 EIO (Input/output error)
    18:38:29.472140 ptrace(PTRACE_POKETEXT, 25015, 0x61fa8168c0, 0xffffffffffffffcc) = -1 EIO (Input/output error)
    18:38:29.472159 ptrace(PTRACE_CONT, 25015, 0, SIG_0) = 0


I haven't looked at the memleax source code, and so I'll see if I can figure out why this is failing.  All of the files and processes are owned by me, and gdb has no problems attaching breakpoints, etc..  I'm also not seeing any indication of SIGALRM timer setup (just a call to rt_sigaction()), although I haven't checked the memleax source code to see how that's set up.  I'll look more into this, tomorrow.

**Comment by WuBingzheng** [comment]
It's my fault not to check the return value of `ptrace()` in memleax.

From the man page of ptrace, errno EIO of PTRACE_POKETEXT means the address (0x61fb07aa50) is invalid. But I am not know the exact reason.

The versions of linked libraries in my system are `libelf-0.164.so`, `libdw-0.164.so`, and `libunwind.so.8.0.1`.
GDB parse the elf and dwarf itself and does not use there libraries, so it's possible that these libraries are not ok.
Maybe you could try this on a new and clean CentOS 6 system.

**Comment by darrylo** [comment]
OK, I'm not very familiar with ELF, but the issue is that, for some reason, the symbol addresses are not being  computed correctly in `symtab.c`.  In `symtab_build_section()`, you have:

    sym->address = esym->st_value + offset;

Unfortunately, for me, `esym->st_value` is the absolute virtual memory address, and is not an offset from `offset`.  I have no idea why I'm getting an absolute address, while you get an offset on your systems.  Looking at `symtab_build_file()`, `offset` comes from:

    uintptr_t offset = hdr->e_type == ET_EXEC ? 0 : start;

Unfortunately, for my `/lib64/libc-2.12.so`, `hdr->e_type == ET_DYN`, and is not `ET_EXEC`.

I've kludged around this by changing:

    sym->address = esym->st_value + offset;

to:

    if (esym->st_value < offset) {
        sym->address = esym->st_value + offset;
    } else {
        sym->address = esym->st_value;
    }

However, this is obviously not a correct fix.

**Comment by WuBingzheng** [comment]
Thank you very much for the debugging. It's very useful.

It seems that the dynamic libraries in your system are loaded in fixed address.
I am not sure of this case. I will check it later.

**Comment by WuBingzheng** [comment]
Would you like to help me again to:

1. paste the result in your system of the command: 

        readelf --sections /lib64/libc-2.12.so

2. paste the result in your system after running a.out:

        cat /proc/`pgrep a.out`/maps

3. send the `/lib64/libc-2.12.so` in your system to my mail:wubingzheng@gmail.com.

Thanks

**Comment by darrylo** [comment]
(more in next comment)

    readelf --sections /lib64/libc.so.6

    There are 78 section headers, starting at offset 0x1d6130:

    Section Headers:
      [Nr] Name              Type             Address           Offset
           Size              EntSize          Flags  Link  Info  Align
      [ 0]                   NULL             0000000000000000  00000000
           0000000000000000  0000000000000000           0     0     0
      [ 1] .note.gnu.build-i NOTE             00000030fd800270  00000270
           0000000000000024  0000000000000000   A       0     0     4
      [ 2] .note.ABI-tag     NOTE             00000030fd800294  00000294
           0000000000000020  0000000000000000   A       0     0     4
      [ 3] .gnu.hash         GNU_HASH         00000030fd8002b8  000002b8
           0000000000003990  0000000000000000   A       4     0     8
      [ 4] .dynsym           DYNSYM           00000030fd803c48  00003c48
           000000000000cb10  0000000000000018   A       5     3     8
      [ 5] .dynstr           STRTAB           00000030fd810758  00010758
           0000000000005674  0000000000000000   A       0     0     1
      [ 6] .gnu.version      VERSYM           00000030fd815dcc  00015dcc
           00000000000010ec  0000000000000002   A       4     0     2
      [ 7] .gnu.version_d    VERDEF           00000030fd816eb8  00016eb8
           0000000000000254  0000000000000000   A       5    17     8
      [ 8] .gnu.version_r    VERNEED          00000030fd817110  00017110
           0000000000000030  0000000000000000   A       5     1     8
      [ 9] .rela.dyn         RELA             00000030fd817140  00017140
           00000000000077d0  0000000000000018   A       4     0     8
      [10] .rela.plt         RELA             00000030fd81e910  0001e910
           00000000000000c0  0000000000000018   A       4    11     8
      [11] .plt              PROGBITS         00000030fd81e9d0  0001e9d0
           0000000000000090  0000000000000010  AX       0     0     4
      [12] .text             PROGBITS         00000030fd81ea60  0001ea60
           00000000001218ac  0000000000000000  AX       0     0     32
      [13] __libc_freeres_fn PROGBITS         00000030fd940310  00140310
           000000000000119e  0000000000000000  AX       0     0     16
      [14] __libc_thread_fre PROGBITS         00000030fd9414b0  001414b0
           00000000000002f2  0000000000000000  AX       0     0     16
      [15] .rodata           PROGBITS         00000030fd9417c0  001417c0
           0000000000019250  0000000000000000   A       0     0     32
      [16] .interp           PROGBITS         00000030fd95aa10  0015aa10
           000000000000001c  0000000000000000   A       0     0     16
      [17] .eh_frame_hdr     PROGBITS         00000030fd95aa2c  0015aa2c
           00000000000065ec  0000000000000000   A       0     0     4
      [18] .eh_frame         PROGBITS         00000030fd961018  00161018
           0000000000025994  0000000000000000   A       0     0     8
      [19] .gcc_except_table PROGBITS         00000030fd9869ac  001869ac
           00000000000003f7  0000000000000000   A       0     0     1
      [20] .hash             HASH             00000030fd986da8  00186da8
           00000000000031c4  0000000000000004   A       4     0     8
      [21] .tdata            PROGBITS         00000030fdb8a700  0018a700
           0000000000000010  0000000000000000 WAT       0     0     8
      [22] .tbss             NOBITS           00000030fdb8a710  0018a710
           0000000000000058  0000000000000000 WAT       0     0     8
      [23] .fini_array       FINI_ARRAY       00000030fdb8a710  0018a710
           0000000000000008  0000000000000000  WA       0     0     8
      [24] .ctors            PROGBITS         00000030fdb8a718  0018a718
           0000000000000018  0000000000000000  WA       0     0     8
      [25] .dtors            PROGBITS         00000030fdb8a730  0018a730
           0000000000000010  0000000000000000   A       0     0     8
      [26] __libc_subfreeres PROGBITS         00000030fdb8a740  0018a740
           00000000000000e8  0000000000000000  WA       0     0     8
      [27] __libc_atexit     PROGBITS         00000030fdb8a828  0018a828
           0000000000000008  0000000000000000  WA       0     0     8
      [28] __libc_thread_sub PROGBITS         00000030fdb8a830  0018a830
           0000000000000020  0000000000000000  WA       0     0     8
      [29] .data.rel.ro      PROGBITS         00000030fdb8a860  0018a860
           00000000000032e0  0000000000000000  WA       0     0     32
      [30] .dynamic          DYNAMIC          00000030fdb8db40  0018db40
           00000000000001f0  0000000000000010  WA       5     0     8
      [31] .got              PROGBITS         00000030fdb8dd30  0018dd30
           00000000000002b0  0000000000000008  WA       0     0     8
      [32] .got.plt          PROGBITS         00000030fdb8dfe8  0018dfe8
           0000000000000058  0000000000000008  WA       0     0     8
      [33] .data             PROGBITS         00000030fdb8e040  0018e040
           0000000000001618  0000000000000000  WA       0     0     32
      [34] .bss              NOBITS           00000030fdb8f660  0018f660
           00000000000042c8  0000000000000000  WA       0     0     32
      [35] .gnu.warning.sigs PROGBITS         0000000000000000  0018f660
           000000000000004d  0000000000000000           0     0     32
      [36] .gnu.warning.sigr PROGBITS         0000000000000000  0018f6c0
           000000000000003b  0000000000000000           0     0     32
      [37] .gnu.warning.sigg PROGBITS         0000000000000000  0018f700
           0000000000000039  0000000000000000           0     0     32
      [38] .gnu.warning.tmpn PROGBITS         0000000000000000  0018f740
           0000000000000037  0000000000000000           0     0     32
      [39] .gnu.warning.tmpn PROGBITS         0000000000000000  0018f780
           0000000000000039  0000000000000000           0     0     32
      [40] .gnu.warning.temp PROGBITS         0000000000000000  0018f7c0
           0000000000000038  0000000000000000           0     0     32
      [41] .gnu.warning.sys_ PROGBITS         0000000000000000  0018f800
           0000000000000044  0000000000000000           0     0     32
      [42] .gnu.warning.sys_ PROGBITS         0000000000000000  0018f860
           0000000000000041  0000000000000000           0     0     32
      [43] .gnu.warning.gets PROGBITS         0000000000000000  0018f8c0
           0000000000000039  0000000000000000           0     0     32
      [44] .gnu.warning.getp PROGBITS         0000000000000000  0018f900
           000000000000003a  0000000000000000           0     0     32
      [45] .gnu.warning.setl PROGBITS         0000000000000000  0018f940
           000000000000003a  0000000000000000           0     0     32
      [46] .gnu.warning.re_m PROGBITS         0000000000000000  0018f980
           000000000000003d  0000000000000000           0     0     32
      [47] .gnu.warning.lchm PROGBITS         0000000000000000  0018f9c0
           0000000000000038  0000000000000000           0     0     32
      [48] .gnu.warning.getw PROGBITS         0000000000000000  0018fa00
           000000000000007a  0000000000000000           0     0     32
      [49] .gnu.warning.sstk PROGBITS         0000000000000000  0018fa80
           0000000000000036  0000000000000000           0     0     32
      [50] .gnu.warning.revo PROGBITS         0000000000000000  0018fac0
           0000000000000038  0000000000000000           0     0     32
      [51] .gnu.warning.mkte PROGBITS         0000000000000000  0018fb00
           0000000000000037  0000000000000000           0     0     32
      [52] .gnu.warning.gtty PROGBITS         0000000000000000  0018fb40
           0000000000000036  0000000000000000           0     0     32
      [53] .gnu.warning.stty PROGBITS         0000000000000000  0018fb80
           0000000000000036  0000000000000000           0     0     32
      [54] .gnu.warning.chfl PROGBITS         0000000000000000  0018fbc0
           0000000000000039  0000000000000000           0     0     32
      [55] .gnu.warning.fchf PROGBITS         0000000000000000  0018fc00
           000000000000003a  0000000000000000           0     0     32
      [56] .gnu.warning.bdfl PROGBITS         0000000000000000  0018fc40
           0000000000000039  0000000000000000           0     0     32
      [57] .gnu.warning.__me PROGBITS         0000000000000000  0018fc79
           000000000000005c  0000000000000000           0     0     1
      [58] .gnu.warning.__ge PROGBITS         0000000000000000  0018fce0
           0000000000000039  0000000000000000           0     0     32
      [59] .gnu.warning.inet PROGBITS         0000000000000000  0018fd20
           000000000000003c  0000000000000000           0     0     32
      [60] .gnu.warning.inet PROGBITS         0000000000000000  0018fd60
           000000000000003b  0000000000000000           0     0     32
      [61] .gnu.warning.inet PROGBITS         0000000000000000  0018fda0
           000000000000003d  0000000000000000           0     0     32
      [62] .gnu.warning.inet PROGBITS         0000000000000000  0018fde0
           000000000000003c  0000000000000000           0     0     32
      [63] .gnu.warning.inet PROGBITS         0000000000000000  0018fe20
           000000000000003b  0000000000000000           0     0     32
      [64] .gnu.warning.inet PROGBITS         0000000000000000  0018fe60
           000000000000003b  0000000000000000           0     0     32
      [65] .gnu.warning.getm PROGBITS         0000000000000000  0018fea0
           0000000000000038  0000000000000000           0     0     32
      [66] .gnu.warning.putm PROGBITS         0000000000000000  0018fee0
           0000000000000038  0000000000000000           0     0     32
      [67] .gnu.warning.fatt PROGBITS         0000000000000000  0018ff20
           0000000000000039  0000000000000000           0     0     32
      [68] .gnu.warning.fdet PROGBITS         0000000000000000  0018ff60
           0000000000000039  0000000000000000           0     0     32
      [69] .comment          PROGBITS         0000000000000000  0018ff99
           000000000000002d  0000000000000001  MS       0     0     1
      [70] .shstrtab         STRTAB           0000000000000000  0018ffc6
           0000000000000546  0000000000000000           0     0     1
      [71] .symtab           SYMTAB           0000000000000000  00190510
           000000000002be00  0000000000000018          72   5325     8
      [72] .strtab           STRTAB           0000000000000000  001bc310
           00000000000183e3  0000000000000000           0     0     1
      [73] .gnu_debuglink    PROGBITS         0000000000000000  001d46f4
           0000000000000018  0000000000000000           0     0     4
      [74] .gnu.liblist      GNU_LIBLIST      0000000000000000  001d470c
           0000000000000014  0000000000000014          75     0     4
      [75] .gnu.libstr       STRTAB           0000000000000000  001d4720
           000000000000001d  0000000000000000           0     0     1
      [76] .gnu.prelink_undo PROGBITS         0000000000000000  001d4740
           00000000000014f0  0000000000000001           0     0     8
      [77] .shstrtab         STRTAB           0000000000000000  001d5c30
           00000000000004fc  0000000000000000           0     0     1
    Key to Flags:
      W (write), A (alloc), X (execute), M (merge), S (strings), l (large)
      I (info), L (link order), G (group), T (TLS), E (exclude), x (unknown)
      O (extra OS processing required) o (OS specific), p (processor specific)


    cat /proc/57947/maps

    00400000-00401000 r-xp 00000000 00:19 1269784190                         /a/new/sr/electron/d13/darrylo/a.out
    00600000-00601000 r--p 00000000 00:19 1269784190                         /a/new/sr/electron/d13/darrylo/a.out
    00601000-00602000 rw-p 00001000 00:19 1269784190                         /a/new/sr/electron/d13/darrylo/a.out
    30fd400000-30fd420000 r-xp 00000000 fd:00 2097155                        /lib64/ld-2.12.so
    30fd61f000-30fd621000 r--p 0001f000 fd:00 2097155                        /lib64/ld-2.12.so
    30fd621000-30fd622000 rw-p 00021000 fd:00 2097155                        /lib64/ld-2.12.so
    30fd622000-30fd623000 rw-p 00000000 00:00 0 
    30fd800000-30fd98a000 r-xp 00000000 fd:00 2097561                        /lib64/libc-2.12.so
    30fd98a000-30fdb8a000 ---p 0018a000 fd:00 2097561                        /lib64/libc-2.12.so
    30fdb8a000-30fdb8e000 r--p 0018a000 fd:00 2097561                        /lib64/libc-2.12.so
    30fdb8e000-30fdb90000 rw-p 0018e000 fd:00 2097561                        /lib64/libc-2.12.so
    30fdb90000-30fdb94000 rw-p 00000000 00:00 0 
    30fe800000-30fe883000 r-xp 00000000 fd:00 2097335                        /lib64/libm-2.12.so
    30fe883000-30fea82000 ---p 00083000 fd:00 2097335                        /lib64/libm-2.12.so
    30fea82000-30fea83000 r--p 00082000 fd:00 2097335                        /lib64/libm-2.12.so
    30fea83000-30fea84000 rw-p 00083000 fd:00 2097335                        /lib64/libm-2.12.so
    3101400000-3101416000 r-xp 00000000 fd:00 2097589                        /lib64/libgcc_s-4.4.7-20120601.so.1
    3101416000-3101615000 ---p 00016000 fd:00 2097589                        /lib64/libgcc_s-4.4.7-20120601.so.1
    3101615000-3101616000 rw-p 00015000 fd:00 2097589                        /lib64/libgcc_s-4.4.7-20120601.so.1
    3101c00000-3101ce8000 r-xp 00000000 fd:00 132420                         /usr/lib64/libstdc++.so.6.0.13
    3101ce8000-3101ee8000 ---p 000e8000 fd:00 132420                         /usr/lib64/libstdc++.so.6.0.13
    3101ee8000-3101eef000 r--p 000e8000 fd:00 132420                         /usr/lib64/libstdc++.so.6.0.13
    3101eef000-3101ef1000 rw-p 000ef000 fd:00 132420                         /usr/lib64/libstdc++.so.6.0.13
    3101ef1000-3101f06000 rw-p 00000000 00:00 0 
    7f7855df2000-7f7855df7000 rw-p 00000000 00:00 0 
    7f7855e09000-7f7855e0c000 rw-p 00000000 00:00 0 
    7fffa97ce000-7fffa97e4000 rw-p 00000000 00:00 0                          [stack]
    7fffa97ee000-7fffa97ef000 r-xp 00000000 00:00 0                          [vdso]
    ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by darrylo** [comment]
(Again, I'm not terribly familiar with ELF, so take the following with a large chunk of salt.)

The symbols appear to be encoded using both relative and "absolute" addresses.  Looking at libc, the first few lines of the ELF program header look like (pay attention to the executable `LOAD` line):

    readelf -l /lib64/libc.so.6

    Elf file type is DYN (Shared object file)
    Entry point 0x30fd81ee30
    There are 10 program headers, starting at offset 64

    Program Headers:
      Type           Offset             VirtAddr           PhysAddr
                     FileSiz            MemSiz              Flags  Align
      PHDR           0x0000000000000040 0x00000030fd800040 0x00000030fd800040
                     0x0000000000000230 0x0000000000000230  R E    8
      INTERP         0x000000000015aa10 0x00000030fd95aa10 0x00000030fd95aa10
                     0x000000000000001c 0x000000000000001c  R      10
          [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
      LOAD           0x0000000000000000 0x00000030fd800000 0x00000030fd800000
                     0x0000000000189f6c 0x0000000000189f6c  R E    200000
      LOAD           0x000000000018a700 0x00000030fdb8a700 0x00000030fdb8a700
                     0x0000000000004f58 0x0000000000009228  RW     200000
      DYNAMIC        0x000000000018db40 0x00000030fdb8db40 0x00000030fdb8db40
                     0x00000000000001f0 0x00000000000001f0  RW     8

For the executable `LOAD` line, the `VirtAddr` is `0x00000030fd800000`.  I suppose this is the suggested load address for this shared library.

Next, look at the first few lines of the symbol table (ignoring undefined symbols):

    readelf -s /lib64/libc-2.12.so | grep -v UND

    Symbol table '.dynsym' contains 2166 entries:
       Num:    Value          Size Type    Bind   Vis      Ndx Name
         1: 00000030fd81ea60     0 SECTION LOCAL  DEFAULT   12
         2: 00000030fdb8a700     0 SECTION LOCAL  DEFAULT   21
         9: 00000030fd88d7c0    30 FUNC    GLOBAL DEFAULT   12 __strspn_c1@@GLIBC_2.2.5
        10: 00000030fd86a450   277 FUNC    GLOBAL DEFAULT   12 putwchar@@GLIBC_2.2.5
        11: 00000030fd901ea0    23 FUNC    GLOBAL DEFAULT   12 __gethostname_chk@@GLIBC_2.4

All of the libc symbol values (`esym->st_value`) appear to be "absolute", using the "suggested" load address.  Most of the shared libraries on our RedHat 6 boxes appear to use this "absolute" symbol addressing, which is causing problems for memleax.

However, I've found some libraries that appear to use a "relative" addressing, which is what memleax seems to be expecting.  `/usr/lib/libxcb-keysyms.so` appears to be one.  For this, the first few lines of the program header looks like:

    readelf -l /usr/lib64/libxcb-keysyms.so

    Elf file type is DYN (Shared object file)
    Entry point 0xa50
    There are 6 program headers, starting at offset 64

    Program Headers:
      Type           Offset             VirtAddr           PhysAddr
                     FileSiz            MemSiz              Flags  Align
      LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                     0x0000000000001624 0x0000000000001624  R E    200000
      LOAD           0x0000000000001628 0x0000000000201628 0x0000000000201628
                     0x0000000000000250 0x0000000000000260  RW     200000
      DYNAMIC        0x0000000000001658 0x0000000000201658 0x0000000000201658
                     0x00000000000001a0 0x00000000000001a0  RW     8

The important thing to note is that the executable `LOAD` line has a `VirtAddr` of `0x0000000000000000 ` (zero).  The debug symbols also use relative addressing (from the start of the actual shared library load address):

    readelf -s /usr/lib64/libxcb-keysyms.so | grep -v UND

    Symbol table '.dynsym' contains 32 entries:
       Num:    Value          Size Type    Bind   Vis      Ndx Name
         1: 0000000000000980     0 SECTION LOCAL  DEFAULT    9
        13: 0000000000001150     9 FUNC    GLOBAL DEFAULT   11 xcb_key_press_lookup_keys
        14: 0000000000000bd0    58 FUNC    GLOBAL DEFAULT   11 xcb_key_symbols_free

So, a fix for this would appear to be to first make sure that relative addressing is used for symbol addressing:

    relative_offset = esym->st_value - suggested_load_address_from_header

and then get the actual address using the start of the actual load address:

    sym->address = esym->st_value - suggested_load_address_from_header + offset;

**Comment by WuBingzheng** [comment]
Thanks very much!
I will look into it after work.

**Comment by WuBingzheng** [comment]
I began to learn ELF only for memleax, so I am not familiar with it and the dynamic linking neither.

I searched around and found that you are right. (http://stackoverflow.com/questions/19018776/assignment-of-addresses-in-shared-library)
I assumed that the base address of dynamic library is aways 0. But it may be not!

I have fix the bug and commit to master branch.
Would you like to try it in your system?

Thanks again.

**Comment by WuBingzheng** [comment]
Hi, darrylo. Would you like to try this in your system?
I will release a new version if this is ok.

**Comment by darrylo** [comment]
I can give it a try, but it'll have to wait until next week, sorry.

**Comment by WuBingzheng** [comment]
waiting for your information.

**Comment by darrylo** [comment]
Sorry for the delay.  It seems to be working.

**Comment by WuBingzheng** [comment]
Thanks very much!
