### ISSUE TITLE
Version for i386/32 bits

### ISSUE THREAD

**Issue by nkoch61** [WuBingzheng/memleax#19]
Hello.
Is there any technical reason for not having a 32 bit version?
Thank you.

**Comment by WuBingzheng** [comment]
There is no technical reason. I just thought 32-bit is out of date.

Someone asked me the same question via email. I gave a patch. But I did not test it much. You may try it.

[memleax-32bit.628432bcd3.patch.txt](https://github.com/WuBingzheng/memleax/files/1221131/memleax-32bit.628432bcd3.patch.txt)

**Comment by nkoch61** [comment]
Thanks a lot. I'll try it.

Am 14.08.2017 04:27 schrieb WuBingzheng: 

> There is no technical reason. I just thought 32-bit is out of date. 
> 
> Someone asked me the same question via email. I gave a patch. But I did not test it much. You may try it. 
> 
> memleax-32bit.628432bcd3.patch.txt [1] 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1]
https://github.com/WuBingzheng/memleax/files/1221131/memleax-32bit.628432bcd3.patch.txt
[2]
https://github.com/WuBingzheng/memleax/issues/19#issuecomment-322086636
[3]

**Comment by nkoch61** [comment]
With the enclosed patches it seams like memleax runs under FreeBSD 10.3
/ i386 with Clang-Compiler.
I tested it with a small program which leaks and the reported call stack
and error position
seem to be correct.

The patch for using kinfo_getvmmap() is not required for 10.3 but for
9.1.

I tried to get memleax to work under FreeBSD 9.1 but only got error
messages:

 No symbol table found
 No debug-line found

I think that comes from either libelf or libdwarf being too old:
 libdwarf-20130207
 Name : libdwarf
 Version : 20130207
 Installed on : Mon Aug 14 09:25:51 2017 CEST
 Origin : devel/libdwarf
 Architecture : freebsd:9:x86:32

 libelf-0.8.13_2
 Name : libelf
 Version : 0.8.13_2
 Installed on : Mon Aug 14 09:25:44 2017 CEST
 Origin : devel/libelf
 Architecture : freebsd:9:x86:32

I tried with gcc4.2.1 (system compiler) and with gcc4.8.5. 

Am 14.08.2017 04:27 schrieb WuBingzheng: 

> There is no technical reason. I just thought 32-bit is out of date. 
> 
> Someone asked me the same question via email. I gave a patch. But I did not test it much. You may try it. 
> 
> memleax-32bit.628432bcd3.patch.txt [1] 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1]
https://github.com/WuBingzheng/memleax/files/1221131/memleax-32bit.628432bcd3.patch.txt
[2]
https://github.com/WuBingzheng/memleax/issues/19#issuecomment-322086636
[3]

**Comment by WuBingzheng** [comment]
I use the same versions of libelf and libdwarf in FreeBSD 10.3.
Does the patch work in 10.3, but not in 9.1 ?
I am too busy to debug this these days. Maybe later.

**Comment by nkoch61** [comment]
Yes, seems to work under 10.3.

Am 18.08.2017 02:40 schrieb WuBingzheng: 

> I use the same versions of libelf and libdwarf in FreeBSD 10.3.
> Does the patch work in 10.3, but not in 9.1 ?
> I am too busy to debug this these days. Maybe later. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/WuBingzheng/memleax/issues/19#issuecomment-323230065
[2]

**Comment by WuBingzheng** [comment]
I have port memleax into x86, and pushed it to master branch.
I did not test it at FreeBSD 9.1 (I have no this envirement), but it may work.
Would you like to test it?

**Comment by nkoch61** [comment]
Thank you very much for porting. Yes I will test it.

Am 10.10.2017 03:36 schrieb WuBingzheng: 

> I have port memleax into x86, and pushed it to master branch.
> I did not test it at FreeBSD 9.1 (I have no this envirement), but it may work.
> Would you like to test it? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/WuBingzheng/memleax/issues/19#issuecomment-335334031
[2]
