### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [WuBingzheng/memleax#2]
I would like to point out that identifiers like "[`_MLD_BREAKPOINT_`](https://github.com/WuBingzheng/memleax/blob/6329353d432921e63da44e7c62c6236b7a4ac21e/breakpoint.h)" and "[`_MEMLEAKDETECTOR_`](https://github.com/WuBingzheng/memleax/blob/b13b72de1302e12d4f343e3a0eb4aeada5f3dbf1/memleax.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by WuBingzheng** [comment]
I did not know this programming rule.
I will change my code later, and read the total coding standard.
Thanks very much.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/WuBingzheng/memleax/commit/8f2c550df5f691e3036fb5460e1901224e466715 "Renaming of include guards").
