### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by MagmaiKH** [WuBingzheng/memleax#21]
Are there any plans to add aarch64 support?
It won't cross-build but building on target I got it to configure but the compile fails with:

cc -DMLX_AARCH64 -DMLX_LINUX -DMLX_WITH_LIBDW -I/usr/include/elfutils/ -g -O2 -Wall   -c -o breakpoint.o breakpoint.c
In file included from machines.h:4:0,
                 from breakpoint.c:15:
ptrace_utils.h: In function 'ptrace_get_regs':
ptrace_utils.h:25:9: error: 'PTRACE_GETREGS' undeclared (first use in this function)
  ptrace(PTRACE_GETREGS, pid, 0, regs);
         ^
ptrace_utils.h:25:9: note: each undeclared identifier is reported only once for each function it appears in
ptrace_utils.h: In function 'ptrace_set_regs':
ptrace_utils.h:29:9: error: 'PTRACE_SETREGS' undeclared (first use in this function)
  ptrace(PTRACE_SETREGS, pid, 0, regs);
         ^
breakpoint.c: In function 'do_breakpoint_init':
breakpoint.c:75:2: warning: implicit declaration of function 'set_breakpoint' [-Wimplicit-function-declaration]
  set_breakpoint(pid, bp->entry_address, bp->entry_code);
  ^
<builtin>: recipe for target 'breakpoint.o' failed
make: *** [breakpoint.o] Error 1

**Comment by WuBingzheng** [comment]
I have port memleax to aarch64 days ago.
But I have not test it much (only on Raspberry), so not merged it into master.
It's in the 'aarch64' branch.
Please use it and feedback if it's ok.

For some reason, the target program need to be compiled with '-funwind-tables' flag of GCC.
