### ISSUE TITLE
Script to mimic valgrind behaviour?

### ISSUE THREAD

**Issue by ov7a** [WuBingzheng/memleax#22]
It is stated in docs that 

> `Valgrind` starts target process, while `memleax` attaches to a running process;

But what should I do if want to attach to process ASAP? Is there a standard approach for it?

I've tried something like that:
```
#!/bin/bash
$@ &
pid=$!
kill -s STOP $pid
memleax -m1 -e1 $pid
kill -s CONT $pid
wait $pid
```
But I've get either a segfault or the following error:
`Error in open /proc/pid/maps: No such file or directory`

**Comment by WuBingzheng** [comment]
Try this:

```
#!/bin/bash
$@ &
pid=$!
memleax -m1 -e1 $pid
```

**Comment by ov7a** [comment]
I still get `Error in open /proc/pid/maps: No such file or directory`. Perhaps the problem is that program halts before `memleax` is attached to it.

**Comment by WuBingzheng** [comment]
It works for me.
Maybe the target process starts slower on your machine.
Try to sleep a while before invoking memleax:

```
#!/bin/bash
$@ &
pid=$!
sleep 0.5
memleax -m1 -e1 $pid
```

**Comment by WuBingzheng** [comment]
Does your program exit immediately after starting?
If yes, then there should be no memory leak of your program.

**Comment by ov7a** [comment]
`sleep 0.5` didn't help.
Yes, the program exits almost immediately after starting. Seems like `memleax` is not appropriate tool for my use-case.
