### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [WuBingzheng/memleax#3]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [callstack_string](https://github.com/WuBingzheng/memleax/blob/4f27d2f9a7c3e2ad6d2989e77ee167fddb18b317/callstack.c#L41)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output.") ⇒ [main](https://github.com/WuBingzheng/memleax/blob/8147c225e4a909e8cdaff74a5e86a87197b02ea0/memleax.c#L72)

**Comment by WuBingzheng** [comment]
I will handle the return value of malloc() later.
printf()? do you mean sprintf()?

Thanks

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more. Would you like to detect every error situation as early as possible?

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for your software?

**Comment by WuBingzheng** [comment]
When writing programs for production, I check every return value of library APIs which may fail, such as malloc, snprintf. I know this is important.
But this is a tool for fun, and not used widely. So I didn't handle it well at beginning. I will improve this in future, and other code analysis also.

Thanks for you advice.

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by WuBingzheng** [comment]
I didn't heard AOP before. I take a glance at it and think I have to spend some time to understand it.
I will response later.
Thanks.

**Comment by elfring** [comment]
Do you find information sources like the following useful?
* Article "[A Reusable Aspect for Memory Allocation Checking](https://web.archive.org/web/20120220075303/http://research.msrg.utoronto.ca/ACC/Tutorial#A_Reusable_Aspect_for_Memory_All "AspectC Tutorial")"
* Document "[Aspect-Oriented Software Development - An Introduction](https://web.archive.org/web/20130512025224/http://www.info.ucl.ac.be/~jbrichau/courses/introductionToAOSD.pdf "AOSD")" by Johan Brichau and Theo D'Hondt
* Paper "[On Typesafe Aspect Implementations in C++](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.125.2164 "AspectC++")" by Daniel Lohmann and Olaf Spinczyk
