### ISSUE TITLE
== Attach process error:: Operation not permitted

### ISSUE THREAD

**Issue by tst-basilhuffman** [WuBingzheng/memleax#41]
I keep getting this when trying to tun memleax. Its a call to ptrace, and here is probably not the place for this, but if you have any guidance as to why this is the case, please let me know.

**Comment by WuBingzheng** [comment]
Did you try `sudo`, or this [answer](https://stackoverflow.com/a/32274645)?

**Comment by tst-basilhuffman** [comment]
Sudo did the trick for certain process. I will close this issue. A different one has popped up.
