### ISSUE TITLE
centos 6x64 and 7x64

### ISSUE THREAD

**Issue by macvk** [WuBingzheng/memleax#44]
Can't compile under centos.

cmake reporting error:
None of the required 'libelf' found
Could not find libdw or libdwarf

but these libraries are installed:
yum install elfutils-libelf-devel
yum install libdwarf-devel

**Comment by WuBingzheng** [comment]
Could you try to checkout commit e1e7266a71656b35b7316ddca9ce904ab45dc4c5, which still uses ./configure?

**Comment by macvk** [comment]
[root@node3 memleax-e1e7266a71656b35b7316ddca9ce904ab45dc4c5]# ./configure
checking machine type...
checking OS type...
checking libraries...
checking libunwind...
checking libelf...
libelf-devel is missing.
Error: libelf-devel is required.
[root@node3 memleax-e1e7266a71656b35b7316ddca9ce904ab45dc4c5]# yum list installed | grep libelf
elfutils-libelf.x86_64           0.172-2.el7                     @base

**Comment by macvk** [comment]
it's working fine. you should include it in readme.

**Comment by WuBingzheng** [comment]
OK, thanks.

I do not want to maintain memleax any more because it's complex.
Would you like to try [libleak](https://github.com/WuBingzheng/libleak), and give some comment?

**Comment by macvk** [comment]
I have done my task using valgrind, sorry I don't have time to try the libleak now. will keep it in mind and try it in the future.
