### ISSUE TITLE
Compilation steps on Ubuntu 16.04

### ISSUE THREAD

**Issue by jarun** [WuBingzheng/memleax#5]
I couldn't compile it on Ubuntu 16.04 **with libdwarf enabled**.
Please provide the steps in README.

**Comment by WuBingzheng** [comment]
I just tried memleax on Ubuntu 16.04.
There seems no `libdwarf` in Ubuntu. I find `libdw1` and `libdwarf-freebsd` instead.
I will figure out them.
Besides, memleax also works **wrong** on Ubuntu for multi-process and multi-thread.
I will fix it as soon as possible.

Thanks for your issue.

**Comment by jarun** [comment]
:+1:

**Comment by WuBingzheng** [comment]
1. I built libdwarf from source, and memleax works well with it.
2. I will add libdw support later, so you can install libdw in Ubuntu by `apt`, and build memleax with it.
3. I have fix the bug of multi-process/thread on Ubuntu. Please checkout the new version code.

**Comment by jarun** [comment]
:+1:

**Comment by WuBingzheng** [comment]
I have added libdw support.
